version: '3.9'

services:

  notebooks:
    container_name: notebooks
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - .:/code